services:
  postgres:
    image: 'postgres:16'
    container_name: 'clinic-postgres'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'PGTZ=UTC'
    ports:
      - '5432:5432'
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  postgres_data:
